### ISSUE TITLE
feature request: Allow pointing the generator at a specific imgui directory

### ISSUE THREAD

**Issue by thomcc** [cimgui/cimgui#169] opened 2020-12-06 08:09 UTC
Right now the generator always uses `../imgui` (that is, the submodule) as the path to the imgui repository. It would be nice if this could be controlled, either by an argument, environment variable (probably slightly easier and avoids breaking any scripts that invoke the generator), etc.

This can be more convenient if imgui is vendored in, if it needs to be modified, and avoids many of the hassles with submodules (which are often painful).

By default it could still do the same thing it does now, of course.

**Comment by sonoro1234** [comment] 2020-12-06 08:50
Nothing prevents you to change imgui submodule at will.
You can even overwrite it with any imgui source without using git at all.

**Comment by sonoro1234** [comment] 2021-03-21 08:29
@thomcc If https://github.com/imgui-rs/imgui-rs/issues/435#issuecomment-803456276 is the cause of doing this feature request there could be an environment variable for the path of imgui.
`IMGUI_PATH` would be ok?

**Comment by thomcc** [comment] 2021-03-21 08:31
Yes, it's related. `IMGUI_PATH` is totally fine, thank you.

**Comment by sonoro1234** [comment] 2021-03-21 08:50
Just pushed. Closing now.
Reopen issue if there is a new related issue.

**Closed by sonoro1234** 2021-03-21 08:50 UTC
Labels: enhancement

**Comment by thomcc** [comment] 2021-03-21 08:52
Wow, that was fast. It probably will be a few weeks before I get a chance to take advantage of it, but thanks!
